services:
  - type: web
    name: delivery-bot-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
  - type: worker
    name: delivery-bot-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py bot
